on: push
jobs:
  lint:
    name: Python linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Pip
        run: apt-get install python3-pip
