on: push
jobs:
  lint:
    name: Python linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
          pip install pylint
          pylint ./*.py
        
